/**
 * IRAAC Have Your Say V1 — canonical immutable definition.
 *
 * Transcribed from docs/survey/IRAAC_HAVE_YOUR_SAY_V1_DRAFT.md (content
 * baseline, per HERMES_DEEPSEEK_BUILD_SUPERPROMPT §8). Do not edit in place:
 * a material change creates a reviewed successor version with a new hash.
 */

import type { SurveyDefinition } from "./types.js";

export const SURVEY_V1: SurveyDefinition = {
  schemaVersion: "1.0.0",
  slug: "have-your-say",
  title: "Have Your Say — IRAAC's got your back",
  introduction:
    "IRAAC listens to Aboriginal communities. What you share helps IRAAC understand what is happening, make practical recommendations to government and report back to community. The survey takes about 8–12 minutes. You can skip any question, stop at any time or complete it without giving your name. Your answers will not affect services you receive.\n\nThis survey is not an emergency or crisis service. If you or someone else is in immediate danger, call 000. If you need culturally safe crisis support, call 13YARN on 13 92 76. You can also speak with an IRAAC worker instead of continuing.",
  sections: [
    {
      id: "A",
      title: "Eligibility, comfort and participation",
      questions: [
        {
          id: "A01",
          section: "A",
          text: "Are you 18 years or older?",
          type: "single_choice",
          options: ["Yes", "No", "Prefer not to say"],
          required: true,
          optional: false,
          preferNotToSay: true,
          rule: "Required before a response session is created. No or Prefer not to say stores no answer and shows a neutral page linking to IRAAC's general human contact pathway. It does not invite a minor to disclose sensitive information.",
        },
        {
          id: "A02",
          section: "A",
          text: "Are you in a safe and private enough place to answer personal questions?",
          type: "single_choice",
          options: [
            "Yes",
            "I would like to skip personal questions",
            "I would rather speak with a person",
            "I need immediate help",
          ],
          required: true,
          optional: false,
          preferNotToSay: false,
          rule: 'Required. "Skip personal questions" skips B04–B07, D04–D09 and F01–F03 while retaining B01–B03, C01–C03, D01–D03, G01–G04 and H01–H06. "Speak with a person" stops the questionnaire and shows the general human pathway. "Immediate help" stops normal questions and shows approved urgent-help choices. Every adapter uses the same fixture.',
        },
        {
          id: "A03",
          section: "A",
          text: "How are you completing this survey today?",
          type: "single_choice",
          options: [
            "By myself online",
            "With an IRAAC or partner worker",
            "By human phone",
            "By AI-assisted phone",
            "Other approved mode",
          ],
          required: false,
          optional: true,
          preferNotToSay: false,
          rule: "Usually system metadata; confirm only when needed.",
        },
        {
          id: "A04",
          section: "A",
          text: "Are you answering mainly as a community member or on behalf of an organisation/business?",
          type: "single_choice",
          options: ["Community member", "Organisation or business", "Both", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
          rule: "Optional. This does not convert business contact details into personal consent.",
        },
      ],
    },
    {
      id: "B",
      title: "About you",
      intro:
        "These questions help IRAAC understand whose voices are being heard. You can skip anything you do not want to answer. A suburb, town or community is enough; do not give your full address.",
      questions: [
        {
          id: "B01",
          section: "B",
          text: "What suburb, town or community do you live in?",
          type: "text",
          required: false,
          optional: true,
          preferNotToSay: false,
          maxLength: 120,
          rule: "Optional; prevent full-address prompting.",
        },
        {
          id: "B02",
          section: "B",
          text: "Are you of Aboriginal or Torres Strait Islander origin?",
          type: "single_choice",
          options: [
            "Aboriginal",
            "Torres Strait Islander",
            "Both Aboriginal and Torres Strait Islander",
            "Neither",
            "Prefer not to say",
          ],
          required: false,
          optional: true,
          preferNotToSay: true,
          rule: "Optional; final wording requires community review and alignment with the ABS standard.",
        },
        {
          id: "B03",
          section: "B",
          text: "What age group are you in?",
          type: "single_choice",
          options: ["18–24", "25–34", "35–44", "45–54", "55–64", "65–74", "75+", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
        },
        {
          id: "B04",
          section: "B",
          text: "How do you describe your gender?",
          type: "single_choice",
          options: ["Woman", "Man", "Non-binary", "I use a different term", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
          rule: "Optional; show a short self-description only after “different term”.",
        },
        {
          id: "B05",
          section: "B",
          text: "What is your current work or study situation?",
          type: "multi_choice",
          options: [
            "Working full-time",
            "Working part-time or casually",
            "Looking for work",
            "Studying or training",
            "Caring for family or community",
            "Unable to work right now",
            "Retired",
            "Other",
            "Prefer not to say",
          ],
          required: false,
          optional: true,
          preferNotToSay: true,
          rule: "Optional; select all that apply.",
        },
        {
          id: "B06",
          section: "B",
          text: "What is the highest level of education or training you have completed?",
          type: "single_choice",
          options: [
            "Primary school",
            "Some secondary school",
            "Year 12",
            "Certificate or trade",
            "Diploma",
            "University degree or higher",
            "Other",
            "Prefer not to say",
          ],
          required: false,
          optional: true,
          preferNotToSay: true,
        },
        {
          id: "B07",
          section: "B",
          text: "What is your current household income range before tax?",
          type: "single_choice",
          options: [
            "Under $25,000",
            "$25,000–$49,999",
            "$50,000–$74,999",
            "$75,000–$99,999",
            "$100,000 or more",
            "Not sure",
            "Prefer not to say",
          ],
          required: false,
          optional: true,
          preferNotToSay: true,
          rule: "Optional. Review ranges before launch and report only in safe aggregates.",
        },
      ],
    },
    {
      id: "C",
      title: "IRAAC awareness and connection",
      questions: [
        {
          id: "C01",
          section: "C",
          text: "Before today, how much had you heard about IRAAC?",
          type: "single_choice",
          options: ["A lot", "A little", "I had heard the name", "Nothing", "Not sure"],
          required: false,
          optional: true,
          preferNotToSay: false,
        },
        {
          id: "C02",
          section: "C",
          text: "Which IRAAC programs or ways to connect have you heard of or used?",
          type: "multi_choice",
          options: [
            "MCC",
            "YouthScape",
            "The Crew",
            "DARC",
            "Have Your Say",
            "Book a Call",
            "Drop In",
            "Home Visit",
            "None yet",
            "Not sure",
            "Other",
          ],
          required: false,
          optional: true,
          preferNotToSay: false,
          rule: "Optional; select all.",
        },
        {
          id: "C03",
          section: "C",
          text: "How would you prefer to take part with IRAAC?",
          type: "multi_choice",
          options: [
            "Online",
            "Email",
            "Text message",
            "Phone",
            "Face to face",
            "Home/community visit",
            "Community event",
            "Not sure",
            "Other",
          ],
          required: false,
          optional: true,
          preferNotToSay: false,
          rule: "Optional. This preference is not contact permission.",
        },
      ],
    },
    {
      id: "D",
      title: "Community priorities and recent experience",
      intro:
        "Thinking about the last month, tick anything that matters to you. This is not a diagnosis. You can skip the whole section.",
      questions: [
        {
          id: "D01",
          section: "D",
          text: "Over the last month, how have things been going overall?",
          type: "single_choice",
          options: ["Going well", "Mostly okay", "Some days have been hard", "Really struggling", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
        },
        {
          id: "D02",
          section: "D",
          text: "Which areas have mattered to you, your family or community recently?",
          type: "multi_choice",
          options: [
            "Housing or homelessness",
            "Food",
            "Money or bills",
            "Work",
            "Education or training",
            "Transport",
            "Physical health",
            "Social and emotional wellbeing",
            "Alcohol, drugs or gambling",
            "Family support",
            "Feeling safe",
            "Domestic or family violence",
            "Police, courts, bail, prison or returning to community",
            "Disability support",
            "Aged care",
            "Young people",
            "Culture and connection",
            "Racism or discrimination",
            "Access to services",
            "Other",
            "None of these",
            "Prefer not to say",
          ],
          required: false,
          optional: true,
          preferNotToSay: true,
          rule: "Optional; select all. None and Prefer not to say are exclusive.",
          exclusiveOptions: ["None of these", "Prefer not to say"],
        },
        {
          id: "D03",
          section: "D",
          text: "Which three areas should IRAAC raise most strongly with government?",
          type: "multi_choice",
          options: [
            "Housing or homelessness",
            "Food",
            "Money or bills",
            "Work",
            "Education or training",
            "Transport",
            "Physical health",
            "Social and emotional wellbeing",
            "Alcohol, drugs or gambling",
            "Family support",
            "Feeling safe",
            "Domestic or family violence",
            "Police, courts, bail, prison or returning to community",
            "Disability support",
            "Aged care",
            "Young people",
            "Culture and connection",
            "Racism or discrimination",
            "Access to services",
            "Other",
          ],
          required: false,
          optional: true,
          preferNotToSay: false,
          maxSelections: 3,
          rule: "Optional; maximum three. Topic choices from D02 only. Exclude None of these and Prefer not to say; those non-topic responses remain available only in D02.",
        },
        {
          id: "D04",
          section: "D",
          text: "Over the last month, have you felt stressed about money or paying for things you need?",
          type: "single_choice",
          options: ["Not at all", "A little", "Sometimes", "Often", "Most days", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
        },
        {
          id: "D05",
          section: "D",
          text: "Over the last month, has your housing or accommodation felt stable?",
          type: "single_choice",
          options: ["Yes", "Mostly", "Not sure", "No", "I do not currently have stable housing", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
        },
        {
          id: "D06",
          section: "D",
          text: "Over the last month, have you had enough food and healthy meals?",
          type: "single_choice",
          options: ["Yes, most days", "Sometimes", "Not often", "No", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
        },
        {
          id: "D07",
          section: "D",
          text: "Over the last month, have you had someone you trust to talk to?",
          type: "single_choice",
          options: ["Yes", "Sometimes", "Not really", "No", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
        },
        {
          id: "D08",
          section: "D",
          text: "Over the last month, how has your social and emotional wellbeing been?",
          type: "single_choice",
          options: ["Strong", "Mostly okay", "Up and down", "Not good", "Very difficult", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
          rule: "Treat as an operational check-in, not a validated clinical measure.",
        },
        {
          id: "D09",
          section: "D",
          text: "Over the last month, have alcohol, drugs, gambling or another addiction been causing problems for you or someone close to you?",
          type: "single_choice",
          options: ["No", "A little", "Sometimes", "Often", "I am worried about this", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
        },
      ],
    },
    {
      id: "E",
      title: "Conditional priority detail",
      intro:
        "You said these areas matter. For each one, you can tell us a little more — or skip ahead.",
      questions: [
        {
          id: "E01",
          section: "E",
          text: "What is getting in the way in this area?",
          type: "multi_choice",
          options: [
            "Cost",
            "Waiting time",
            "Transport or distance",
            "Not knowing where to go",
            "Not feeling culturally safe",
            "Not being eligible",
            "Paperwork or digital access",
            "Previous bad experience",
            "No suitable service",
            "Family or caring responsibilities",
            "Other",
            "Prefer not to say",
          ],
          required: false,
          optional: true,
          preferNotToSay: true,
          rule: "Optional; select all. Repeat against stable topic ID, not by copying a new question.",
          repeatFor: { questionId: "D03", max: 3 },
        },
        {
          id: "E02",
          section: "E",
          text: "What support or change would help most in this area?",
          type: "text",
          required: false,
          optional: true,
          preferNotToSay: false,
          maxLength: 1000,
          rule: "Plain-language paragraph; discourage names, full addresses and unnecessary identifying details.",
          repeatFor: { questionId: "D03", max: 3 },
        },
        {
          id: "E03",
          section: "E",
          text: "Have you tried to get help with this in the last month?",
          type: "single_choice",
          options: ["Yes and it helped", "Yes but it did not help enough", "I am still waiting", "No", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
          repeatFor: { questionId: "D03", max: 3 },
        },
      ],
    },
    {
      id: "F",
      title: "Safety-sensitive branch",
      intro:
        "A couple of quick check-ins. You can skip these too. If you would rather not continue here, use the quick exit or speak with an IRAAC worker.",
      questions: [
        {
          id: "F01",
          section: "F",
          text: "Are you safe to continue answering on this device or call?",
          type: "single_choice",
          options: ["Yes", "No", "Not sure", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
          rule: "Optional but shown first. If not safe, offer quick exit and approved safe help; do not send a revealing follow-up.",
        },
        {
          id: "F02",
          section: "F",
          text: "Would you like to see or hear safe support options now?",
          type: "single_choice",
          options: ["Yes", "No", "Prefer not to say"],
          required: false,
          optional: true,
          preferNotToSay: true,
          rule: "Provide 000 for immediate danger and the approved specialist/human pathways.",
        },
        {
          id: "F03",
          section: "F",
          text: "Would you like an IRAAC worker to contact you about support?",
          type: "single_choice",
          options: ["Yes", "Maybe later", "No"],
          required: false,
          optional: true,
          preferNotToSay: false,
          rule: "Optional. Yes continues to safe-contact details and express permission; it does not itself create permission.",
        },
      ],
    },
    {
      id: "G",
      title: "Voice, aspirations and government message",
      questions: [
        {
          id: "G01",
          section: "G",
          text: "What is one thing you wish your community had that is not there now?",
          type: "text",
          required: false,
          optional: true,
          preferNotToSay: false,
          maxLength: 1000,
        },
        {
          id: "G02",
          section: "G",
          text: "If you could say one thing directly to government, what would it be?",
          type: "text",
          required: false,
          optional: true,
          preferNotToSay: false,
          maxLength: 1000,
        },
        {
          id: "G03",
          section: "G",
          text: "What is one change that would make life better over the next year?",
          type: "text",
          required: false,
          optional: true,
          preferNotToSay: false,
          maxLength: 1000,
        },
        {
          id: "G04",
          section: "G",
          text: "Is there anything working well that government and services should protect or build on?",
          type: "text",
          required: false,
          optional: true,
          preferNotToSay: false,
          maxLength: 1000,
        },
        {
          id: "G05",
          section: "G",
          text: "Is there anything important this survey did not ask about, or an issue IRAAC should explore?",
          type: "text",
          required: false,
          optional: true,
          preferNotToSay: false,
          maxLength: 1000,
          rule: "State before the field that this is not an emergency service and only a successfully submitted response is reviewed. Every non-empty G05 response enters trained human triage; an LLM cannot make the safety decision. If trained-review capacity is exceeded, disable G05 for new sessions and show the approved human contact pathway.",
        },
      ],
    },
    {
      id: "H",
      title: "Support and follow-up",
      questions: [
        {
          id: "H01",
          section: "H",
          text: "Would you like IRAAC to follow up about anything you shared?",
          type: "single_choice",
          options: ["Yes, please contact me", "Maybe, show me the choices", "No, I just wanted to share"],
          required: true,
          optional: false,
          preferNotToSay: false,
          rule: "Required only to determine follow-up. No skips contact fields.",
        },
        {
          id: "H02",
          section: "H",
          text: "What kind of support would help you take part?",
          type: "multi_choice",
          options: [
            "Transport",
            "Interpreter or language support",
            "Accessibility support",
            "Help completing the survey",
            "Face-to-face conversation",
            "Home or community visit",
            "Program information",
            "Referral information",
            "Other",
            "No support needed",
          ],
          required: false,
          optional: true,
          preferNotToSay: false,
          rule: "Optional; select all.",
        },
        {
          id: "H03",
          section: "H",
          text: "What name would you like us to use?",
          type: "text",
          required: false,
          optional: true,
          preferNotToSay: false,
          maxLength: 120,
          rule: "Optional unless needed for requested follow-up.",
        },
        {
          id: "H04",
          section: "H",
          text: "How may IRAAC contact you about this request?",
          type: "multi_choice",
          options: ["Email", "SMS", "Human phone call"],
          required: false,
          optional: true,
          preferNotToSay: false,
          rule: "Optional, unticked choices. At least one is required only when H01 is Yes.",
          showWhen: { kind: "equals", questionId: "H01", value: "Yes, please contact me" },
        },
        {
          id: "H05",
          section: "H",
          text: "What email address or phone number should IRAAC use?",
          type: "text",
          required: false,
          optional: true,
          preferNotToSay: false,
          maxLength: 200,
          rule: "Validated contact fields shown only for chosen H04 channels. Required only for the chosen follow-up route. Store separately from answers, ask the person to confirm it and use a neutral verification message before recurring or sensitive contact.",
          showWhen: { kind: "answered", questionId: "H04" },
        },
        {
          id: "H06",
          section: "H",
          text: "Is there a safe or preferred time and way to contact you?",
          type: "text",
          required: false,
          optional: true,
          preferNotToSay: false,
          maxLength: 300,
          rule: 'Short answer plus “Do not leave voicemail” and “Do not identify the topic in a message” choices.',
        },
      ],
    },
  ],
  contactPermissions: [
    {
      id: "I01",
      text: "Email me IRAAC newsletters and invitations to future surveys.",
      note: "Optional. Withdraw any time via the link in every email or by contacting IRAAC.",
    },
    {
      id: "I02",
      text: "Send me SMS invitations to future surveys.",
      note: "Optional and separate from email. Reply STOP at any time.",
    },
    {
      id: "I03",
      text: "An IRAAC worker may call me about future surveys.",
      note: "Optional and separate from AI.",
    },
    {
      id: "I04",
      text: "An IRAAC AI assistant may call me about future surveys. The call will identify itself as AI and I can ask for a person or end the call.",
      note: "Optional, specific and separate. Final wording requires legal/privacy approval.",
    },
    {
      id: "I05",
      text: "If IRAAC later proposes recording or retaining a phone transcript, ask me for separate permission at that time.",
      note: "Preference only; it is not advance recording consent.",
    },
  ],
};
